[build]
publish = "build"
command = "yarn build"


[[redirects]]
  from = "/sponsors"
  to = "https://sponsors.gitnation.org/jsnationlive/:splat"
  status = 301
  force = true
  headers = {X-From = "Netlify"}
